CREATE TABLE IF NOT EXISTS User
(
    UserId       INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Username     TEXT    NOT NULL UNIQUE,
    PasswordHash TEXT    NOT NULL,
    FirstName    TEXT    NOT NULL,
    LastName     TEXT    NOT NULL,
    CreatedAt    DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Project
(
    ProjectId   INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId      INTEGER     NOT NULL,
    ProjectName TEXT UNIQUE NOT NULL,
    FOREIGN KEY (UserId) REFERENCES User (UserId)
);

CREATE TABLE IF NOT EXISTS Task
(
    TaskId      INTEGER PRIMARY KEY AUTOINCREMENT,
    TaskName    TEXT NOT NULL,
    TaskContent TEXT
);

CREATE TABLE IF NOT EXISTS ProjectTasks
(
    ProjectId INTEGER NOT NULL,
    TaskId    INTEGER NOT NULL,
    FOREIGN KEY (ProjectId) REFERENCES Project (ProjectId),
    FOREIGN KEY (TaskId) REFERENCES Task (TaskId),
    PRIMARY KEY (ProjectId, TaskId)
);
