CREATE TABLE IF NOT EXISTS User
(
    UserId       INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Username     TEXT    NOT NULL UNIQUE,
    PasswordHash TEXT    NOT NULL,
    FirstName    TEXT    NOT NULL,
    LastName     TEXT    NOT NULL,
    CreatedAt    DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Project
(
    ProjectId       INTEGER PRIMARY KEY AUTOINCREMENT,
    ProjectName     TEXT    NOT NULL,
    -- IsAutoGenerated: Boolean
    IsAutoGenerated INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Task
(
    TaskId      INTEGER PRIMARY KEY AUTOINCREMENT,
    TaskName    TEXT NOT NULL,
    TaskContent TEXT,
    Duration    INTEGER, -- Duration in minutes
    DueDate     DATE
);

CREATE TABLE IF NOT EXISTS UserProject
(
    UserId    INTEGER        NOT NULL,
    ProjectId INTEGER UNIQUE NOT NULL,
    FOREIGN KEY (UserId) REFERENCES User (UserId) ON DELETE CASCADE,
    FOREIGN KEY (ProjectId) REFERENCES Project (ProjectId) ON DELETE CASCADE,
    PRIMARY KEY (UserId, ProjectId)
);

CREATE TABLE IF NOT EXISTS ProjectTask
(
    ProjectId INTEGER        NOT NULL,
    TaskId    INTEGER UNIQUE NOT NULL,
    FOREIGN KEY (ProjectId) REFERENCES Project (ProjectId) ON DELETE CASCADE,
    FOREIGN KEY (TaskId) REFERENCES Task (TaskId) ON DELETE CASCADE,
    PRIMARY KEY (ProjectId, TaskId)
);
