INSERT INTO User(Username, PasswordHash, FirstName, LastName)
VALUES
-- Password: 123456789
('example', '$2y$10$MNk8/gyP8PLbvIAhvpGmn.aCEPPUSjjphcOk5Cl6FSsjfAEieD4uq', 'Max', 'Mustermann'),
-- Password: secure
('smail', '$2y$10$KcZCHT19UYibSdQGsDhtuuWOnfO6CYc14Obrc4f0Y0s5y5R.WJeiW', 'Smail', 'Müller');

INSERT INTO Project(ProjectName)
VALUES ('GitHub Projects'),
       ('Groceries'),
       ('Finances');

INSERT INTO Project(ProjectName, IsAutoGenerated)
VALUES ('Inbox', 1),
       ('Today', 1),
       ('Upcoming', 1),
       ('Deleted', 1),
       ('Completed', 1),
       ('Inbox', 1),
       ('Today', 1),
       ('Upcoming', 1),
       ('Deleted', 1),
       ('Completed', 1);

INSERT INTO Task(TaskName, TaskContent, Duration, DueDate)
VALUES ('Artificial General Intelligence', 'Build a world dominating AI.', 2400, '2021-12-31 13:45:00');

INSERT INTO Task(TaskName, TaskContent)
VALUES ('How to get rich',
        '1. Make Website
2. Make money
3. Buy fancy stuff'),
       ('Buy Stocks', 'TSLA, AAPL, GOOG, SMAIL'),
       ('Linux Kernel', 'Rewrite whole kernel in Rust');

INSERT INTO Task(TaskName)
VALUES ('Tomatoes'),
       ('Popcorn'),
       ('Pizza'),
       ('Mozzarella'),
       ('TODO Webapp');

INSERT INTO UserProject(UserId, ProjectId)
VALUES (1, 1),
       (1, 2),
       (2, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (1, 7),
       (1, 8),
       (2, 9),
       (2, 10),
       (2, 11),
       (2, 12),
       (2, 13);

INSERT INTO ProjectTask(ProjectId, TaskId)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (2, 4);
